Homework 1 - Khlamov Ilya
ok-technopolis-autumn-2022/Ilya_Khlamov pull request #1
Opened 2022-10-02 12:43 UTC by Coo3n

2022-10-03 08:49 UTC, fromanywhere requested changes
Изучите, пожалуйста, глубже назначение форм и как они работают
В нашей работене будет ошибкой, если останется одна форма, но нужно хорошо понимать, где и зачем она будет нужна

2022-10-03 08:49 UTC, fromanywhere commented on index.html
> +                    <form method="input">
нет такого method

2022-10-03 08:49 UTC, fromanywhere commented on index.html
> +                                <input type="checkbox" id="switch" value="1"/>
Почему здесь value = 1? Есть ли смысл в id?

2022-10-03 08:49 UTC, fromanywhere commented on index.html
> +                            </label>
Здесь внутри label два интерактивных элемента. Куда будет ставиться фокус на клик? Есть ли смысл в такой группировке?

2022-10-03 08:49 UTC, fromanywhere commented on index.html
> +                            <form method="remove-todo">
такого method нет, и в целом я не очень вижу смысл в использовании формы тут

2022-10-03 08:49 UTC, fromanywhere commented on index.html
> +                                    <span class="remove-todo-btn-text">x</span>
Вложенный span не нужен.

Конечно, ничего не сломается, но лишняя разметка = лишний код = сложнее поддержка

2022-10-13 22:56 UTC, Coo3n commented on index.html
> +                    <form method="input">
[fromanywhere](https://github.com/fromanywhere), исправил полностью код.

2022-10-13 22:56 UTC, Coo3n commented on index.html
> +                                <input type="checkbox" id="switch" value="1"/>
[fromanywhere](https://github.com/fromanywhere), исправил полностью код.

2022-10-13 22:56 UTC, Coo3n commented on index.html
> +                            </label>
[fromanywhere](https://github.com/fromanywhere), исправил полностью код.

2022-10-13 22:56 UTC, Coo3n commented on index.html
> +                            <form method="remove-todo">
[fromanywhere](https://github.com/fromanywhere), исправил полностью код.

2022-10-13 22:56 UTC, Coo3n commented on index.html
> +                                    <span class="remove-todo-btn-text">x</span>
[fromanywhere](https://github.com/fromanywhere), исправил полностью код.

2022-10-14 07:09 UTC, fromanywhere approved these changes

2022-10-18 12:32 UTC, merged