Homework2 - CSS
ok-technopolis-autumn-2022/Ilya_Khlamov pull request #2
Opened 2022-11-21 22:40 UTC by Coo3n

2022-11-22 08:43 UTC, fromanywhere requested changes

2022-11-22 08:43 UTC, fromanywhere commented on Style/style.css
> +img, picture {
но у нас нет ни одной картинки на проекте

2022-11-22 08:43 UTC, fromanywhere commented on Style/style.css
> +    font-family: sans-serif;
а зачем такое определение на уровне span?

2022-11-22 08:43 UTC, fromanywhere commented on Style/style.css
> +    margin-block-start: 0;
предлагается использовать более традиционные свойства

2022-11-22 08:43 UTC, fromanywhere commented on Style/style.css
> +    width: 28px;
кладем картинку фоном

2022-11-22 08:43 UTC, fromanywhere commented on Style/style.css
> +    box-shadow: inset 0px -1px 0px #0003;
это должен быть border

2022-11-22 08:43 UTC, fromanywhere commented on Style/style.css
> +.task-item__view:hover > button {
а фокус?

2022-11-22 08:43 UTC, fromanywhere commented on Style/style.css
> +    border: 1px solid #5DC2AF;
а фокус?

2022-11-22 08:43 UTC, fromanywhere commented on Style/style.css
> +    width: 560px;
очень много ширин, заданных руками. Было бы достаточно жить от ширины фрейма приложения

2022-11-22 08:43 UTC, fromanywhere commented on Style/style.css
> +    width: 518px;
здесь тоже про ручной размер — есть более гибкие варианты

2022-11-22 08:43 UTC, fromanywhere commented on Style/style.css
> +    display: none;
недоступно с клавиатуры

2022-11-22 08:43 UTC, fromanywhere commented on Style/style.css
> +    font-family: Roboto;
нет смысла описывать шрифт отдельным узлам — унаследуйте от базового

2022-11-22 08:43 UTC, fromanywhere commented on Style/style.css
> +    width: 542px;
опять какая-то ширина

2022-11-22 08:43 UTC, fromanywhere commented on Style/style.css
> +    display: none;
снова недоступно с клавиатуры

2022-11-22 21:42 UTC, Coo3n commented on Style/style.css
> +img, picture {
Убрал

2022-11-22 21:43 UTC, Coo3n commented on Style/style.css
> +    font-family: sans-serif;
Исправил, сделал на уровне body

2022-11-22 21:43 UTC, Coo3n commented on Style/style.css
> +    margin-block-start: 0;
Cделал нормально c margin

2022-11-22 21:44 UTC, Coo3n commented on Style/style.css
> +    width: 28px;
Исправил, однако мне казалось, что img вписался лучше

2022-11-22 21:45 UTC, Coo3n commented on Style/style.css
> +    box-shadow: inset 0px -1px 0px #0003;
В макете сделано это через box-shadow, с border будет выглядеть все иначе

2022-11-22 21:45 UTC, Coo3n commented on Style/style.css
> +.task-item__view:hover > button {
Добавил

2022-11-22 21:45 UTC, Coo3n commented on Style/style.css
> +    width: 560px;
Убрал

2022-11-22 21:45 UTC, Coo3n commented on Style/style.css
> +    width: 518px;
Убрал

2022-11-22 21:45 UTC, Coo3n commented on Style/style.css
> +    border: 1px solid #5DC2AF;
Добавил

2022-11-22 21:45 UTC, Coo3n commented on Style/style.css
> +    font-family: Roboto;
Исправил

2022-11-22 21:46 UTC, Coo3n commented on Style/style.css
> +    display: none;
Теперь виден через tab

2022-11-22 21:46 UTC, Coo3n commented on Style/style.css
> +    width: 542px;
Убрал

2022-11-22 21:46 UTC, Coo3n commented on Style/style.css
> +    display: none;
Теперь виден через tab

2022-11-23 10:23 UTC, fromanywhere commented on Style/style.css
> +    box-shadow: inset 0px -1px 0px #0003;
то, что в макете оно там нарисовано через тень — это фантазии дизайнера. В браузере отрисовка через тень будет стоить на рендере дороже, чем бордер

2022-11-23 10:23 UTC, fromanywhere commented on Style/style.css
> +    display: none;
У меня вот так 
<img width="615" alt="image" src="https://user-images.githubusercontent.com/1042969/203523222-46fe610f-afbe-481c-b050-ac7170efe322.png">

2022-11-23 10:24 UTC, fromanywhere commented on Style/style.css
> +    width: 28px;
<img width="625" alt="image" src="https://user-images.githubusercontent.com/1042969/203523366-eced4c66-a6bf-4541-983c-31e2ce660f15.png">

Теперь делаем размер кнопки больше, чтобы можно было попасть пальцем

2022-11-26 18:21 UTC, Coo3n commented on Style/style.css
> +    box-shadow: inset 0px -1px 0px #0003;
Исправил, теперь буду знать

2022-11-26 18:22 UTC, Coo3n commented on Style/style.css
> +    display: none;
[fromanywhere](https://github.com/fromanywhere), исправил теперь точно видно

2022-11-26 18:22 UTC, Coo3n commented on Style/style.css
> +    width: 28px;
[fromanywhere](https://github.com/fromanywhere), охват кнопки изменил, теперь лучше

2022-11-28 09:18 UTC, fromanywhere approved these changes
Зачтено

2022-11-28 09:18 UTC, fromanywhere commented on Style/style.css
> +    display: flex;
Может быть вот так 
<img width="679" alt="image" src="https://user-images.githubusercontent.com/1042969/204239425-d8bf025f-6237-49c5-ada8-87d56303b02a.png">

Чтобы такого не было, здесь нужно дописать min-width: 0;

2022-11-28 09:18 UTC, fromanywhere commented on Style/style.css
> +    color:#666666;
На узких экранах так 
<img width="425" alt="image" src="https://user-images.githubusercontent.com/1042969/204239757-c01130c5-1f88-4be6-999b-b461a09b74f0.png">

Имеет смысл здесь min-width: 600px;

2022-11-28 12:43 UTC, Coo3n commented on Style/style.css
> +    display: flex;
Готово

2022-11-28 12:43 UTC, Coo3n commented on Style/style.css
> +    color:#666666;
Готово

2022-11-28 12:43 UTC, merged